---
apiVersion: v1
kind: Namespace
metadata:
  name: nightingale
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-mem-limits
  namespace: nightingale
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 512Mi
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightingale
  namespace: nightingale
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.nightingale-server: glob:master-*
    flux.weave.works/tag.migrate: glob:master-*
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nightingale
  template:
    metadata:
      labels:
        app: nightingale
    spec:
      imagePullSecrets:
      - name: kube-pull
      containers:
      - name: nightingale
        image: harbor.nightingale.revelry.org/library/nightingale:master-8c2afb1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: nightingale-env-config
        - secretRef:
            # This secret is created by KubeDB along with the db instance
            # The secret name follows the pattern {Postgres resource name}-auth
            name: nightingale-database-auth
        - secretRef:
            name: nightingale-env-secret
        env:
        # distributed elixir via libcluster
        - name: CLUSTER_ENABLED
          value: "1"
        # let each instance know its own IP for distributed elixir
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      initContainers:
      - name: migrate
        image: harbor.nightingale.revelry.org/library/nightingale:master-8c2afb1
        command: ["./bin/nightingale"]
        args: ["eval", "Nightingale.ReleaseTasks.migrate()"]
        envFrom:
        - configMapRef:
            name: nightingale-env-config
        - secretRef:
            # This secret is created by KubeDB along with the db instance
            # The secret name follows the pattern {Postgres resource name}-auth
            name: nightingale-database-auth
        - secretRef:
            name: nightingale-env-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nightingale
  namespace: nightingale
spec:
  selector:
    app: nightingale
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
# This 'headless service' lets app nodes discover one another through DNS
# enabling distributed elixir features
apiVersion: v1
kind: Service
metadata:
  name: nightingale-nodes
  namespace: nightingale
spec:
  clusterIP: None
  selector:
    app: nightingale
  ports:
  - name: epmd
    port: 4369
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nightingale
  namespace: nightingale
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: nightingale-server.nightingale.revelry.org
    http:
      paths:
      - path: /
        backend:
          serviceName: nightingale
          servicePort: 80
  tls:
  - hosts:
    - nightingale-server.nightingale.revelry.org
    secretName: nightingale-cert
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: nightingale-database
  namespace: nightingale
spec:
  version: "postgis-10.2"
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
  backupSchedule:
    cronExpression: "@every 1h"
    storageSecretName: nightingale-s3-secret
    s3:
      endpoint: "s3.amazonaws.com"
      bucket: rev-nightingale-kubedb
      prefix: nightingale
---
apiVersion: v1
data:
  # used for url helpers and socket security checks
  APP_DOMAIN: nightingale-server.nightingale.revelry.org
  # should match the 'app:' label in the deployment
  APP_NAME: nightingale
  POSTGRES_HOSTNAME: nightingale-database
  PORT: "5000"
kind: ConfigMap
metadata:
  creationTimestamp:
  name: nightingale-env-config
  namespace: nightingale
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: nightingale-s3-secret
  namespace: nightingale
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCHgN33e3kgzwWk6hZvvyijk9YrOuI/neicZl4hdsSQOMOoAYYjb6HaL3jbay8WtOkGVWUMSv/rXcOr4yqICygxm/gDc8v6E8tqLRlyKtP7LLN6OizmuqBw7lBw4div3OTv2k8HNPg8SGHPVcEyHFKEJRX7xfVpMeS2Qp4i/POa3rrTyQYlqoQM12JD5hsHf+C5vJbM9Ze+55cS8HE9Z0se/Af1qHkNc6LGyR32WEiGpk3FWCHAOpi9KSUPnoqNlFezmBsgIcneVA4W2xDuj5bfxqZq+tKt4fb+5kkOhKvVg3gM6AGTNbpVlc31+4S4qA5Xgk1wfjMv1KUKzQY5L//B8zKKl6WRlDfu3MSUFfUVTfHZmntvvLJ4a+zfAD9Cpp/uAR8tvr2rSQ7lCPlfoP6mL9jffHRGEMGEUI6+SUuZduLuAuxbVJpW5cUIMkG8zQOto4eEQZAuO6tz2PhNuQZsMpUlVGE+1CtrtI1/MAJFmnqfgCr+0VIcHm4+hG1qZnIF/tBmD0L/Kb4rR4T0acOquhGebJ7fsyIxBBEv39LImSwr0RQfEIDZ57qFBtk61y4GKRXkfvI9wlGkd2R8b2jUJUXiCFnSm8/du8SfLFzKObV9mP2KVIhDqrYST2o9Bk91QKGtDasgqLbi9U/8+wQD8CZcyRMqKVVgIDIIl96LkThxqbc4lIm1LgHxbyeZqACpGnTVp9tGjAIXbY9SB3AB6XiD6A==
    AWS_SECRET_ACCESS_KEY: AgCce4wruhQeN5ikYXn/gJknzIUinC4pdkC7aUdcybYyd2iEdIhdS71sJ/BbXBKoTWLvjqVZFV0ABKR7msoq2n94hhjQg3V22vRYl5fXmOTgSfrhXEt94hImBvHEnU0k/tQ3Xp2NAGeUFEulPlXOPn/4JiMeqKKevLSA3y7gDndJ6ROZqjONaG81gYXS38nIPspaQ6ZzFaPlokPP8/lGtPdyxTCvE/sTei/QTfLloBdvxA1DjBsXsIuSME1gShyVjPq4nWMzF76dkL29hG6D56KmQ8q0BW2EamuBdiTJrQhHNYELZf2NAVfXDac+LgTD1L+P66404JTa9dAjEiWxX29QYrmTsmrv22Cq6MwaL7qcFlFZjjsUvRV+heok676WMY65VadUC1r6b/MO2dt9fFcimHSt6v5Ne3TPGHNCZdC+ivhvHY0fGEWG/ggsc/c1c5Eqhk2Ee6xjuxi69vDpuQxgsBP47dtbPjnLnK420MgcjdiXuVIw0dxx5xsv5N8YFUHTTrmAK6unkjOlCRMf/TAl1mqERJ/i2YprOjacsquttBQvLlUafU+xUcqcLeyky1ANgVtvlOwvpVFmQqxPLuiAriY9Ic7oISiPElUd171ULcDoxDd5BrZDaCwEO4hYSKt/0kJ0RtHgm5GHpejjOvtZz53eJZeoY1o43s3UCB+hn6SV1J86k5cfB1PrwvPaE6Z11ybUqa/g+BCee5hXVp5vgFiz66+kz7Gmn53N+hQmVUkOzwtiH8IE
  template:
    metadata:
      name: nightingale-s3-secret
      namespace: nightingale
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: kube-pull
  namespace: nightingale
spec:
  encryptedData:
    .dockerconfigjson: AgBLVPOVdMNUG30ArsZXmsdfRfud+mJSSCjxSyUna3n3b5KKvou7c7ozmFkd+JrAAzzcO7pZYDsItg4lr9KknfBi+VOTQzF8Es/9537mnGRJT4lgFiu45Y67J1HLW3IsmKrmevCzp+UzB8heM7RQ0O9RP5A7+P7FwNRtc+xEYGOu5E2HIDK2OhG0foMcK3Xm5Z+iQee/IWubm4qYTM3v8Ck2y42TTquDmSA3QN1CMbuzf0Bu4WuyX2MyLuzYl2gR3/0QHhLThvlEnP0QmLEHNtkSWiyeVIU5j/Oi26qdjQQHpnc0uAswPxrYminepnQlfI5Qpv5OFzjl/V8z7lUUahrsjtxF62QxDikR7OiPzb6KJXkxkUmloH0dKk5C5lXsiuu94/jWFCaKDAfHbs4yxgu+TfOwUH7m+OjeE2WEg+9/BmsxvDCzMhnZ+Log3l7RqdETB4v65SpPG8vvieNYtvMYDO+LI5EyAyTbX1jgZPBR9iT6tzbfiPZfOjUyGla6fss2G7ic5fZXLYvckFYLkPsNFKwNZnFWe7FfZ40ifgbZIf7iGKQSq+alGT7EzoOGFRp/ahkP3BXVQWpgkwIVpS60h/3wXgx9RgrA658CNG8pzTH6+ww2pQYGkN4d0Dv/NiCyVQyWEjWxCzTyxGEYI2UX6QSfOTber6vJed6scFRQmZnt3hauSSx75cuQR1tJqZ6vDyCeGN03hn9QcJtq1Gzlot5P+GZUMFUCMtJ8ZAcowxzSVBsXY3hiH4ijpsbDc1X8XUsx5qIFEDxBbXksEficuLpqMq26gO0GIH3k1mHBcs1lin3EzOTinIN8QI3CKn7P8PzDTyK5I8E3aomDzFum//TfQIpqEWsQJcARZq3mczDL+1sSjZ1Z4iqywdKtHDYYeF5tQKDD30C9REozdr5zbi+JrAysDmd/HwvVIkQSsgsH3UqryXuVP+5tlx7iaRAkHzyGEUd7QZgcS8cnKgAV
  template:
    metadata:
      creationTimestamp:
      name: kube-pull
      namespace: nightingale
    type: kubernetes.io/dockerconfigjson
status: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: nightingale-env-secret
  namespace: nightingale
spec:
  encryptedData:
    SECRET_KEY_BASE: AgBCATi/bvkxAtnmcT46Cuh/uBH5/sf0ZZMGRsso+YOdjRzS8d486lHzULRusKgicLcO3mnvk367jbG+7l5sHpKtSaCs3HMj4EFmyvCsh5QbI5XUUmP4K0V5NOFJcufs3ScRcmz3DUWwxjjcYNN7K63D7b2o4yx7Lk4TX8YxsYlrk4t6FNe3t1d8lB7CeAsdfp4GkIZLcqk8rrFBhpYP7S8kA/tTp8+UOFwSoZ+PNzWR8wWFaw1CG/AF4gX13VZ0l/tgiD0iLpqg0IR7J4YpE/BTbl/qEnRVjrfAExAV+9sajvdQ+26sUz7bhMRDmU6GRarD3W/y7TgRhIskvoSo0hRx59FTUVECMMHrvExXihDfm0oHp2Z/8GIYbBcDZGVJ45RADLpuyJXq8X7M/+N0DWHejqDjAyIx0wnqqJ47tC+u79CRhQ5+WFr0zEAMaA8bY+Z/HMEYZt7TodTS44TDQ6NjQKhS4O9eEHamDteiRS7yn7VzePq+2f9bJ+6zEJhEAOGnFKroucssIVkeQm21J74k0U8Z9HI0r0lea/gCBe0xCOaKZNZ/shZPey1SyKDgMPkn290GKIU3LlCRK20aLAPudhyBZJrHbm6b3gIpCAE52///vop9wv+2xLyv7clv22+x7YcTNWJShuQE4ZU+ibITNtwr00/CxUP/n6vaCO1X1lE95scOMtG95MduGQ1YpZmvThBFwAs9yrVbahlM64ltensioAxG9M0G+BsqRGaAlr6371PD9k4fC0Sb2AnQFQMSurHMBozErt7XA2tosDKS
  template:
    metadata:
      creationTimestamp:
      name: nightingale-env-secret
      namespace: nightingale
    type: Opaque
status: {}
