---
apiVersion: v1
kind: Namespace
metadata:
  name: nightingale-staging
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-mem-limits
  namespace: nightingale-staging
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 512Mi
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightingale-staging
  namespace: nightingale-staging
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.nightingale-server: glob:master-*
    flux.weave.works/tag.migrate: glob:master-*
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nightingale-staging
  template:
    metadata:
      labels:
        app: nightingale-staging
    spec:
      imagePullSecrets:
      - name: kube-pull
      containers:
      - name: nightingale-staging
        image: harbor.nightingale.revelry.org/library/nightingale-server:master-latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: nightingale-staging-env-config
        - secretRef:
            name: nightingale-staging-env-secret
        - secretRef:
            # This secret is created by KubeDB along with the db instance
            # The secret name follows the pattern {Postgres resource name}-auth
            name: nightingale-staging-database-auth
        env:
        # distributed elixir via libcluster
        - name: CLUSTER_ENABLED
          value: "1"
        # let each instance know its own IP for distributed elixir
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      initContainers:
      - name: migrate
        image: harbor.nightingale.revelry.org/library/nightingale-server:master-latest
        command: ["./bin/nightingale"]
        args: ["eval", "Nightingale.ReleaseTasks.migrate()"]
        envFrom:
        - configMapRef:
            name: nightingale-staging-env-config
        - secretRef:
            # This secret is created by KubeDB along with the db instance
            # The secret name follows the pattern {Postgres resource name}-auth
            name: nightingale-staging-database-auth
---
apiVersion: v1
kind: Service
metadata:
  name: nightingale-staging
  namespace: nightingale-staging
spec:
  selector:
    app: nightingale-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
# This 'headless service' lets app nodes discover one another through DNS
# enabling distributed elixir features
apiVersion: v1
kind: Service
metadata:
  name: nightingale-staging-nodes
  namespace: nightingale-staging
spec:
  clusterIP: None
  selector:
    app: nightingale-staging
  ports:
  - name: epmd
    port: 4369
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nightingale-staging
  namespace: nightingale-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: nightingale-server-staging.nightingale.revelry.org
    http:
      paths:
      - path: /
        backend:
          serviceName: nightingale-staging
          servicePort: 80
  tls:
  - hosts:
    - nightingale-server-staging.nightingale.revelry.org
    secretName: nightingale-staging-cert
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: nightingale-staging-database
  namespace: nightingale-staging
spec:
  version: "11.2"
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
  backupSchedule:
    cronExpression: "@every 1h"
    storageSecretName: nightingale-staging-s3-secret
    s3:
      endpoint: "s3.amazonaws.com"
      bucket: rev-nightingale-kubedb
      prefix: nightingale-staging
---
apiVersion: v1
data:
  # used for url helpers and socket security checks
  APP_DOMAIN: nightingale-server-staging.nightingale.revelry.org
  # should match the 'app:' label in the deployment
  APP_NAME: nightingale-staging
  POSTGRES_HOSTNAME: nightingale-staging-database
  PORT: "5000"
kind: ConfigMap
metadata:
  creationTimestamp:
  name: nightingale-staging-env-config
  namespace: nightingale-staging
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nightingale-staging-s3-secret
  namespace: nightingale-staging
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCv/2dNfz2aEWOboiwPYBq8D9Ej3JYP0mpU7u5UerAyQmqhIWqEoqMsIEyQ0uM/GDTRAJ+/tJ8b56FcIgHzJTvgeF6A786vULk70OrcXkVz4/NYmQmUp4nibKYIhND85MP4a9H5vg700HQHhG12nOILrun2Ojeq55rebZjlx6o8/b0+RIK0TSA02sTDxhFrK1XZ+KmHhh/9/oToSerCaN6bmytY/TxU0paBqPPFOP+meiNz6onlhReXmKEJQkylmyh9HfFunoJ8a2EYHnZNnj4MaxW0bSNmArPA06aGafEu9BLjTomjic5TH0YvL/ksLr4hHI6LgKEpCoIhxle57MYGTUwR8f9D3Soz7DFc81yHW8vpBy99bkSotZb3lxyT7qwbZ5D7zRiYJNuOOsYbjyTBuevcMDJEBw0ktVnSOf4+mtBcJ9PqTSFRV9LMJsTfin4R2Mkx2FTeiYocynymSlpayAdHJttXuXejq87dmOsRnHDG+XVEYMyrn+z2foUlc+BJSsyG+7dXK5ADgzte0zSQk5TQv04+LRpMBU0g1V3DK/9sHjiVmvMy+Pe45dF551fDcVV/mC5+phizoRQLQkLTfTZvATPZQuwWg/VX1M134SEHKigyS85O/sXpN1j261HdUGoAG19zVxzqmzRFPBTLNd5rhh1gORVnZmJH5mGq+6ZFChcOP00wf0vQNP5MIIO+ggxJNiTWObj2GTV/Qi3nCqmeig==
    AWS_SECRET_ACCESS_KEY: AgBxQaZPOExUhsvF4QIeXnJU53xOSs3/H9kfewaVto6dj73/SbNTjcXCmujNL4XzKoIAPctfzp57CKMP09aJmESxUqo3xtIkQgGN+qBovn7pAhcoRDYpnyOhzEpwmEMsFQeRMyAVzTWpM7sLG4SpXolhHHr3R7nbBo77X8KEo3lmv9YaSQgijLU/UeF4W6dkeU17vz7iuGc5ylj0IKitVWY42m/kj9zkkjAwG0tfBpiH1QBXg5OayWgwNuosatXcTth8GILRdtdSQo/C/7AChFjr/pkqi3UAUMWWW9y+lKFHxZuVaTiWamd5ivrCM88UGpcMsL3/+1bfGrjSJozh4KLQwGIX/XI52Wwn0QHqLg1MfNn2J/WDXgNJ5DlMHttRkRVZP06fl4IjJbK2sJU3b1PgO6/MEBIxq4GLifMpMsBbgDBjTOSBOWkOdfOkmyOZBmnLx5sDjORjOs3y7iD6V7NR9k/2L2gvP3AFGvS4Elk19EQkehnkNGQjvomqIfsCCo3ojbuEfuz4d/CWYkGbDy2EvvwLwf+usvu5QjuFA9wkycxijvFQM/q0j81/uBW1flc1CybRXbYyW1ChFKJbdZ/Am+K7JAxum4wbOJdbbGiIQHQve8qLsMIy050qhvMMF3EIeo8SJ87jfOD6t4quGnXiEl5LLNrkpZ3tKMQAj6dm6OJ3YlYTmxo7tL9rbdVg5OS58p6trSh6/dvGDTP1vzvtCYlobSb18Ng5diyFm2qZrJzFcQRbO8NE
  template:
    metadata:
      creationTimestamp: null
      name: nightingale-staging-s3-secret
      namespace: nightingale-staging
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-pull
  namespace: nightingale-staging
spec:
  encryptedData:
    .dockerconfigjson: AgBpk/PmUHI9Pyx7+QLLpTT5JlETafRoBEErm+Loh4QG6sL9qgJzu4q4YED0Jw4FI9GbweI+YS7q38U1aLU0Vhg3MNZvQ4Zne49hdYGHR62+vqKoV1DAhqbjLBEnjUw01DSWPnrbNj9883lfz4EQwXD3ZqOTavnJ9v782j36VbJaY/QsQI9yg0akAhTRsYv85NwbNjh+XX2CPeZJoCGguXXZSZ+XdIeWwSoM/wSCEwYs3lo67VFKzxjIra5HikPykpkNrhWe8Lubh5ZyHlHDR7ut3DDqc8BUUZBtwWx8qBe+qpUeOiaXZINT2O+Or7iOcw0R5GPka7N+XyB7AcTeiSetHx4ZrCw3gCvXQ6gSoCeVNMfcTI7390kjOm9TTA2mbHGTc8UAjQRPEMINx1qz3pRU8WrqPy0Js/LuMt3C8MtMYl0G0Q+ONIoNtAE56JKQY0u1ykQDFBBOp3R4NtQNf+78Rtfa6+hhX5RHp1kd/H2T2wslCmZMpbZjsMouV7cEjpzVz4PeiGYUlTc9yaOWts396LaJySdaA9qGrkuY5BjiUoSbgHYbML9OesGZfnBcZmsSu1uugMs98wKIlWmYCVvoU5swfTgFTUDDDePaV5HcFF/7/pHOh2a8DZ16Bukzv990zNThpgOc2PZgatvbBisn3mXqdVDJmaQINeMYlifWlwE29VGFkjB7vDJt0GDayuuGNaFjaJOo+pHlywWJ3ELaTlwGJPRNVQoMteDpc2GlsAjE7M/sKOtLGoINZqIZWPzmtA9+5dX/rPWKmOYs9lZs00m5OcA+PxN5ZOKC4VdncM8PUuDHhLXnUgyidPi4Bzfu1VWwStyloUNvlCu6FLSh/9M0edcbBzPPblgOX5IJDfWZoFf81agqFwljI+n0jIy8aK3eQVvI/cJKOW5z7npxs0M3rWTbQkngshcxqliszNOmzpFU/aBlAn9+mLMrqn6IUET+j5NdYrqditMuHNTm
  template:
    metadata:
      creationTimestamp: null
      name: kube-pull
      namespace: nightingale-staging
    type: kubernetes.io/dockerconfigjson
status: {}
