---
# Source: moondog/templates/kubedb/kubedb.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: md-kubedb
---
# Source: moondog/templates/kubedb/kubedb.yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubedb
  namespace: md-kubedb
spec:
  timeout: 1600
  releaseName: md-kubedb
  chart:
    repository: https://charts.appscode.com/stable/
    name: kubedb
    version: v0.12.0
  values:
    apiserver:
      healthcheck:
        enabled: false 
    enableAnalytics: false
---
# Source: moondog/templates/kubedb/kubedb.yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubedb-catalog
  namespace: md-kubedb
spec:
  timeout: 1600
  releaseName: md-kubedb-catalog
  chart:
    repository: https://charts.appscode.com/stable/
    name: kubedb-catalog
    version: v0.12.0
  values: {}
---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: postgis-10.2
spec:
  version: "10.2"
  db:
    image: abkfenris/kubedb-postgis:10.2
  exporter:
    image: kubedb/postgres_exporter:v0.4.6
  tools:
    image: kubedb/postgres-tools:10.2-v2
  podSecurityPolicies:
    databasePolicyName: "postgres-db"
    snapshotterPolicyName: "postgres-snapshot"
