---
# Source: moondog/templates/sealed-secrets/sealed-secrets.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
# Source: moondog/templates/sealed-secrets/sealed-secrets.yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  timeout: 1600
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.7.6
  values:
    rbac:
      pspEnabled: true
