apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-aws-credentials
  namespace: md-velero
spec:
  encryptedData:
    cloud: AgCYi7a7hBufAuThfjnGPY4+Es/u4haW2IZZK0xU1pdIQOGLl6MkfwB5OkCW/g6UXwlliDrLrxlybleBElBAp0SC4D+rydszqXmM+XzKcu8Ud7CkFyEaTcHF63GNvq0UXw44SdU4u0TnUYINcJlmaH7pQQuDrY/iLPsELu5OIAfj0rxBWUU6pj7R3z8wNGNX1tCAfWxa0tgD+F8pGEJUNy2uz/epixRtmZHf9TnJpkkChStBAxKnrkJcnAGKS/AFbcDww2NmAbUoQALFhlfQe3mDM/s2vkJAsAIPX/UWveqBSLgtC2dt7VpmoGjsRTat+dx0mEaH/xDItPOP0xWqC4mFoqx8Ww4SExTKg5604DPBhUTogZqlP/xZWWalgzOx9ImbZUNvgfCQqrsDjgpCh0+lrgHnZNqdmheoG6/AyziZqghIGdAZe9foDQFF3GRo+W1TLUfhDU8vewe63esiYM5jVx3n+ttiyp/7TD/mMPeYcxOpZ6/xTFT8yGICa6LqlmCuaFFvBK00i/Z3MoghKE02Hju6kUNafL8ag/5+oCbubgIAF+fyDk16l5kiycRI2w1dGmTVQm/GPcuhDOHnc8zGLTfXXvEmQS3mxwrIZXqt0qIt/VMecEBT8QSY8sI4S6VZAPOUpm9xw+ls8Bx9H4Ze4DpHWkWMCGyezCshqoHZSdCDoRyHRjHDTd/4OKGt62B/zSLAJ4W8vbwLwxVl6yE3wO6JNvz3W/HI4O9Wwrp7XyyDH8XbY51CGnp999JcUvocJLs6Z2PBw3oxZGznCj26DmuKo/gP2g9w7BTkcRQ8b/q6FTnT8Hwn4Y+IcblZMF6B7qaE+cSCfOtFASTHbiSPxaUzfg==
  template:
    metadata:
      creationTimestamp: null
      name: velero-aws-credentials
      namespace: md-velero
    type: Opaque

