---
# Source: moondog/templates/harbor/harbor.yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: md-harbor
spec:
  timeout: 1600
  releaseName: md-harbor
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: 1.3.1
  valuesFrom:
    - secretKeyRef:
        name: values-yaml
  values:
    expose:
      ingress:
        hosts:
          core: harbor.nightingale.revelry.org
          notary: harbor-notary.nightingale.revelry.org
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt"
      tls:
        notarySecretName: tls-harbor-notary-ingress
        secretName: tls-harbor-ingress
    externalURL: https://harbor.nightingale.revelry.org
    database:
      type: external
      external:
        host: harbor-pg
        username: "postgres"
    redis:
      type: external
      external:
        host: md-harbor-redis-redis-ha-haproxy
