apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: md-harbor
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBQSXWJQ5T2q0+sPXhNZNxI0KyPxMUSLiDNbiVuztXwUQ9zdK+HZNBzv48x2tH2+ipi3eUEasWGw/zx1kA/mgVbV1MBXe4wjzDWvExXK5xnBa+pfLv9wWSExNAadd2wl0u2vWuOAJ+6/u8vanHDzW3I24rs79P8N8NPNtq2oy1/lniPpwL64YFQ4r5daXg/5QZQwxZhhJ9xAHHkgJSvv+z4ygWos3NDwOqrWJTs9lRYMSng0ZCD56pMMDwF/3RHzLR58HfCVEE6aSkW+/tGs4HbTI5dthOopaiKcpCP7/k2jhQtNwy0GMNoXJJm45h9pP6lJ4uG8+15CCvpx9/frawZsPqWBSAxUW4VWQFTNy7YFUNQUAzsgEehLkwU7xgVOfaIlcJ2uBqXcZvOSzo3zVwXPPshRitrw29HFlpNznQz98JwdIEOnCSFclmm1XZ8m/o2Lcd7FoketO+R3FpG+6wd/iq8GPJUjhpoH0Q2dYSGc9InBEJSa2XehyCXL9nr2vqvxvkr2l89IigH0nvUUn4HbwABI0xpsIoO0tdI11BtXvSeGbLQjAmj3FOJp6KiI5/G3S2UgOLtgKxVYmgy2NsNLXzsoGbrN/6P8EWP7K6CNhxLD8V9/Yz6FVP2+v/vPUYyfccp8MnG/FQI/m5molIrA6M+Q1jvOPbcXjKr34OJ44TMqDwD+08xsUWPKUuZt9YA98tsNMMS4mxtd2652f2TTrpQhw==
    AWS_SECRET_ACCESS_KEY: AgARx6xKGEmLUD1uYSErKsuf5Ixtm/WlmYxUuFCSR4q3bLbbAsYKt0Exd2iNNMAsK2gHKrujD6O/26q2oiJhskpkxcVOIqaSL5A3aQP0Dzn0cAwrh69NDrHhcWF+FydvuS3HDQS0YBhd9TUApYnC2a3fuGca9XsZ0D2yvBjOizLYa2cf34ovvBlhyLKVrffEYwpL/D0eUn7QF6XoO0IYfYFQ5c5XPbpO0MPOt4uBJ8BBVy9t4k4BpzQefHkPrrgh7V44vESaXbpFb3FP32AZM3pbdwcgz9pAcduREIWxfUhKscGIoCT3gDwBU2D1lSrue5sEXnPHC90Bt8DeLZQ3yxAPD0C+kq7WqOsSRE6ISIZyGmXMav/9ZZdO6FpSHiOtM/C2sgdOHXNREtram82Zt2TTPQJtAfTT3zkS5WxhjOrJd1f18zkxJ1iGuF4kaRkjQbJYN0fhaI8Fx6FCaHRu06Z/D2U6kB8Y/A8JVrrWG8cTk+9bwoSM2rpEhzokTt/XEfaDCd5J0cD0JIBsmtfB72M09F3hg/ncCtHxXgfk6+tJDr8dCfYoycLeNWF5LfpUkae2BkS1Sm7DQnPaCjd9qbcasbDCiqmKeMWuh9gGCdAs8Iy4bq8QCVYgZGieDSoYFQW8HTp7IIrOhMVHfD/VD1yQnk1rihB5g85hXapixpwbWiwFmG3p3LK44hSYO+4oi7Ym6lPDadJpwp84cyWe4YGLw5NKRsJwETh4z1kkV56T3u1e/nHpt0UZ
  template:
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: md-harbor
    type: Opaque

