---
# Source: moondog/templates/oauth2-proxy/oauth2-proxy.yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: md-oauth2-proxy
spec:
  releaseName: md-oauth2-proxy
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: oauth2-proxy
    version: 2.1.1
  valuesFrom:
    - secretKeyRef:
        name: values-yaml
  values:
    config:
      clientID: "oauth2-proxy"
    extraArgs:
      cookie-domain: .nightingale.revelry.org
      whitelist-domain: .nightingale.revelry.org
      email-domain: "*"
      oidc-issuer-url: https://dex.nightingale.revelry.org
      provider: oidc
      ssl-insecure-skip-verify: false
    ingress:
      enabled: true
      hosts:
        - oauth2-proxy.nightingale.revelry.org
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls:
        - secretName: oauth2-proxy-tls
          hosts:
            - oauth2-proxy.nightingale.revelry.org
